// facts to show in loading screen

List<String> facts = [
  "Studying abroad allows you to immerse yourself in a different culture, experience new customs, and try out unique foods and traditions.",
  "Living in a foreign country provides a great opportunity to learn or improve a new language by using it in daily life.",
  "You can build an international network of friends, classmates, and professional contacts that may be valuable in your future career.",
  "Studying abroad challenges you to step out of your comfort zone, fostering personal growth, adaptability, and independence.",
  "Different countries offer diverse educational systems, teaching styles, and academic programs, giving you a chance to explore new learning methods.",
  "Being in a new part of the world makes it easier to explore neighboring countries and regions, expanding your horizons even further.",
  "Many international universities host cultural events, festivals, and workshops, providing insights into local arts, music, and traditions.",
  "You might have access to courses and subjects that aren't available in your home country, allowing you to broaden your academic experience.",
  "Studying abroad can make your resume stand out, demonstrating qualities like adaptability, cross-cultural communication, and global awareness to potential employers.",
  "If you have ancestral roots in a particular country, studying abroad can be an opportunity to reconnect with your heritage.",
  "Trying authentic local cuisine can be a delicious adventure, and you might discover new favorite dishes.",
  "Living in a different country gives you the chance to explore historical sites and landmarks you might have only read about.",
  "Navigating life in a foreign country encourages you to be resourceful and independent in managing tasks like budgeting, grocery shopping, and transportation.",
  "Forming friendships with people from various backgrounds can broaden your perspective and give you a deeper understanding of global issues.",
  "You might discover new interests and hobbies that are popular in your host country, like traditional dances, sports, or arts and crafts.",
  "Participating in local celebrations, holidays, and customs can provide a deeper understanding of the culture and its values.",
  "Overcoming challenges such as language barriers or unfamiliar systems can enhance your problem-solving skills.",
  "You'll experience diverse teaching methods, which can help you develop a well-rounded perspective on education.",
  "Living among people with different cultural norms helps develop cultural sensitivity and empathy, important skills in our interconnected world.",
  "Studying abroad often creates lifelong memories and stories you'll cherish and share for years to come.",
  "Moving to a new country or place often involves a period of cultural adjustment, which can lead to feelings of excitement, confusion, frustration, and eventually adaptation.",
  "When moving to a new place, individuals may experience shifts in their cultural identity as they navigate between their home culture and the culture of the new place.",
  "It's common to experience homesickness when living abroad, as familiar surroundings, friends, and family are suddenly distant. This feeling usually lessens over time as one adapts.",
  "Learning a new language or dealing with language barriers can impact self-confidence and communication skills, which can affect overall psychological well-being.",
  "Moving to a new place can lead to feelings of social isolation, especially initially, as individuals may not have established a support network or close relationships.",
  "Adapting to new cultural norms, customs, and behaviors can be stressful and lead to misunderstandings or anxiety, but it can also foster personal growth.",
  "Living in a different way of life can lead to a phenomenon known as 'positive disorientation,' where individuals reevaluate their assumptions and habits.",
  "The challenges of moving can foster personal growth, resilience, and adaptability as individuals learn to navigate new situations and environments.",
  "Moving can prompt individuals to explore and redefine aspects of their identity, such as values, beliefs, and personal goals.",
  "The anticipation of a move can trigger a mix of emotions, including excitement about new opportunities and anxiety about the unknown.",
  "Experiencing a different way of life can lead to a phenomenon known as 'positive disorientation,' where individuals reevaluate their assumptions and habits.",
  "Being in a new environment often requires increased self-reliance and decision-making, leading to a sense of personal autonomy.",
  "Navigating change necessitates developing effective stress coping strategies, which can have long-lasting benefits for mental well-being.",
  "Returning to one's home country after an extended period abroad can also trigger a form of culture shock, as individuals have adapted to different norms.",
  "Exposure to diverse cultures can stimulate creativity by offering new ways of thinking and problem-solving.",
  "Successfully adapting to a new environment can build resilience, increasing the ability to handle future challenges.",
  "Being in a new environment often requires increased self-reliance and decision-making, leading to a sense of personal autonomy.",
  "Navigating life in a foreign country encourages you to be resourceful and independent in managing tasks like budgeting, grocery shopping, and transportation.",
  "Interacting with people from diverse backgrounds can improve social skills, emotional intelligence, and communication abilities.",
  "Living in a new culture highlights the relativity of cultural norms, challenging one's assumptions and encouraging a broader perspective on values and behaviors.",
  "Experiencing a different way of life can lead to a phenomenon known as 'positive disorientation,' where individuals reevaluate their assumptions and habits.",
  "Living in a different environment encourages mindfulness and being present in the moment, as individuals navigate unfamiliar situations."
];
